name: mosdenv
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pip
  - pytest
  - pandas
  - uncertainties
  - scipy
  - tqdm
  - openmc
  - seaborn
  - jinja2
  - pip:
      - -e .
      - https://github.com/terrapower/armi/archive/main.zip
