name: Tester
on: [push, pull_request]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install wget
        run: sudo apt-get update && sudo apt-get install -y wget

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: mosdenv
          auto-activate-base: false
      
      - name: Restore cached data
        id: cache-data
        uses: actions/cache@v4
        with:
          path: mosden/data/unprocessed
          key: data-cache-${{ hashFiles('download_data.sh') }}

      - name: Run download script if cache miss
        if: steps.cache-data.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run: bash download_data.sh

      - name: Install MoSDeN
        shell: bash -l {0}
        run: |
          pip install -e .

      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest -vv -m "not openmc"